-- Reversible: drop the views and tables in reverse dependency order, then the enums.
create type public.well_type as enum ('borewell', 'open_well', 'tank', 'pond');
create type public.well_status as enum ('active', 'inactive', 'decommissioned');
create type public.well_visibility as enum ('private', 'admin_area', 'public');
create type public.node_status as enum ('provisioning', 'active', 'offline', 'fault', 'retired');
create type public.reading_quality as enum ('good', 'suspect', 'bad');

create extension if not exists postgis with schema extensions;

create table public.wells (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references public.profiles(id) on delete set null,
  admin_area_id uuid not null references public.admin_areas(id) on delete restrict,
  name text not null,
  well_type public.well_type not null,
  latitude double precision not null,
  longitude double precision not null,
  location extensions.geography(point, 4326)
    generated always as (
      extensions.st_setsrid(extensions.st_makepoint(longitude, latitude), 4326)::extensions.geography
    ) stored,
  total_depth_m numeric(8, 3),
  installed_at date,
  status public.well_status not null default 'active',
  visibility public.well_visibility not null default 'private',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wells_name_nonempty check (length(trim(name)) > 0),
  constraint wells_latitude_valid check (latitude between -90 and 90),
  constraint wells_longitude_valid check (longitude between -180 and 180),
  constraint wells_total_depth_positive check (total_depth_m is null or total_depth_m > 0)
);

comment on table public.wells is 'Water sources monitored by JalMaps; all depth measurements are in metres.';
comment on column public.wells.location is 'PostGIS geography point generated from longitude and latitude for nearby-well queries.';

create index wells_admin_area_id_idx on public.wells(admin_area_id);
create index wells_location_gist_idx on public.wells using gist(location);
create index wells_owner_id_idx on public.wells(owner_id);

create table public.nodes (
  id uuid primary key default gen_random_uuid(),
  well_id uuid not null references public.wells(id) on delete cascade,
  hardware_id text not null unique,
  api_key_hash text unique,
  sensor_model text,
  range_m numeric(8, 3),
  hang_depth_m numeric(8, 3),
  calibration_offset_m numeric(8, 3) not null default 0,
  firmware_version text,
  battery_v numeric(6, 3),
  signal_rssi integer,
  last_seen_at timestamptz,
  status public.node_status not null default 'provisioning',
  is_simulated boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nodes_hardware_id_nonempty check (length(trim(hardware_id)) > 0),
  constraint nodes_api_key_sha256 check (
    api_key_hash is null or api_key_hash ~ '^[0-9a-f]{64}$'
  ),
  constraint nodes_range_positive check (range_m is null or range_m > 0),
  constraint nodes_hang_depth_positive check (hang_depth_m is null or hang_depth_m > 0),
  constraint nodes_battery_nonnegative check (battery_v is null or battery_v >= 0)
);

comment on table public.nodes is 'Sensor hardware registered to a well; API credentials are stored only as SHA-256 hashes.';
comment on column public.nodes.is_simulated is 'True for development/simulator hardware; seeded wells use simulated nodes.';
comment on column public.nodes.hang_depth_m is 'Sensor depth below the well reference point, in metres.';

create index nodes_well_id_idx on public.nodes(well_id);
create index nodes_status_last_seen_idx on public.nodes(status, last_seen_at desc);

create table public.readings (
  id bigint generated by default as identity primary key,
  node_id uuid not null references public.nodes(id) on delete cascade,
  recorded_at timestamptz not null,
  received_at timestamptz not null default now(),
  column_m numeric(9, 3) not null,
  depth_to_water_m numeric(9, 3),
  current_ma numeric(9, 3),
  battery_v numeric(6, 3),
  rssi integer,
  quality public.reading_quality not null default 'good',
  raw jsonb not null default '{}'::jsonb,
  constraint readings_column_nonnegative check (column_m >= 0),
  constraint readings_current_nonnegative check (current_ma is null or current_ma >= 0),
  constraint readings_battery_nonnegative check (battery_v is null or battery_v >= 0),
  constraint readings_raw_object check (jsonb_typeof(raw) = 'object'),
  constraint readings_node_recorded_unique unique (node_id, recorded_at)
);

comment on table public.readings is 'Time-series sensor observations; timestamps are UTC and dimensions are in metres.';
comment on column public.readings.depth_to_water_m is 'Depth from the well reference point, captured at ingestion using the node hang depth.';
comment on column public.readings.raw is 'Optional normalized sensor payload; never use this field for API credentials.';

create index readings_node_recorded_desc_idx on public.readings(node_id, recorded_at desc);
