-- Migration for Phase 8: Ingestion API

-- 1. Add api_key_prefix and revoked_at to nodes
alter table public.nodes
  add column api_key_prefix text,
  add column revoked_at timestamptz;

comment on column public.nodes.api_key_prefix is 'Non-secret prefix of the node API key, e.g. jm_live_ABCD, used for lookup.';
comment on column public.nodes.revoked_at is 'If set, the API key is considered revoked and cannot be used.';

create index nodes_api_key_prefix_idx on public.nodes(api_key_prefix);

-- 2. Create ingest_rejects for dead-lettering bad payloads
create table public.ingest_rejects (
  id bigint generated by default as identity primary key,
  node_id uuid references public.nodes(id) on delete set null,
  hardware_id text,
  reason text not null,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  constraint ingest_rejects_reason_nonempty check (length(trim(reason)) > 0)
);

comment on table public.ingest_rejects is 'Dead-letter table for rejected ingestion requests. Payloads must be size-limited by the API before inserting.';

create index ingest_rejects_node_id_received_idx on public.ingest_rejects(node_id, received_at desc);
create index ingest_rejects_received_idx on public.ingest_rejects(received_at desc);

-- 3. Create node_rate_limits table and check function
create table public.node_rate_limits (
  node_id uuid primary key references public.nodes(id) on delete cascade,
  window_start timestamptz not null,
  request_count integer not null default 1,
  constraint node_rate_limits_count_positive check (request_count > 0)
);

comment on table public.node_rate_limits is 'Tracks API requests per minute per node for fixed-window rate limiting.';

create or replace function public.check_node_rate_limit(p_node_id uuid, p_max_reqs integer)
returns boolean
language plpgsql
security definer
as $$
declare
  v_current_minute timestamptz;
  v_count integer;
begin
  v_current_minute := date_trunc('minute', now());

  insert into public.node_rate_limits (node_id, window_start, request_count)
  values (p_node_id, v_current_minute, 1)
  on conflict (node_id) do update
  set request_count = case
                        when public.node_rate_limits.window_start = v_current_minute then public.node_rate_limits.request_count + 1
                        else 1
                      end,
      window_start = case
                       when public.node_rate_limits.window_start = v_current_minute then public.node_rate_limits.window_start
                       else v_current_minute
                     end
  returning request_count into v_count;

  return v_count <= p_max_reqs;
end;
$$;

comment on function public.check_node_rate_limit is 'Fixed-window rate limiter (1 minute window). Returns true if within limit, false if exceeded.';
